name: "update"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  update-jdkforests:
    name: "Update JDK forests"
    runs-on: "ubuntu-20.04"

    steps:
      - name: Downgrade git
        run: |
          # workaround for:
          # https://public-inbox.org/git/20200605224342.GF6569@camp.crustytoothpaste.net/t/
          git --version
          apt-cache policy git
          sudo apt-get install --allow-downgrades git=1:2.25.1-1ubuntu3 git-man=1:2.25.1-1ubuntu3
          git --version
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-corba
          ssh-key: ${{ secrets.JDKFOREST_CORBA_PRIV_KEY }}
          path: jdkforest-corba
          fetch-depth: '0'
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-hotspot
          ssh-key: ${{ secrets.JDKFOREST_HOTSPOT_PRIV_KEY }}
          path: jdkforest-hotspot
          fetch-depth: '0'
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-jaxp
          ssh-key: ${{ secrets.JDKFOREST_JAXP_PRIV_KEY }}
          path: jdkforest-jaxp
          fetch-depth: '0'
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-jaxws
          ssh-key: ${{ secrets.JDKFOREST_JAXWS_PRIV_KEY }}
          path: jdkforest-jaxws
          fetch-depth: '0'
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-jdk
          ssh-key: ${{ secrets.JDKFOREST_JDK_PRIV_KEY }}
          path: jdkforest-jdk
          fetch-depth: '0'
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-langtools
          ssh-key: ${{ secrets.JDKFOREST_LANGTOOLS_PRIV_KEY }}
          path: jdkforest-langtools
          fetch-depth: '0'
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-nashorn
          ssh-key: ${{ secrets.JDKFOREST_NASHORN_PRIV_KEY }}
          path: jdkforest-nashorn
          fetch-depth: '0'
      - uses: actions/checkout@v2
        with:
          repository: ojdk-qa/jdkforest-top
          ssh-key: ${{ secrets.JDKFOREST_TOP_PRIV_KEY }}
          path: jdkforest-top
          fetch-depth: '0'
      - name: Update mirrors
        run: |
          set -eux
          . ./update-funcs.sh
          setup_git_plugin
          update_forest_mirrors "jdk7/jdk7" "jdk7u/jdk7u" "jdk7u/jdk7u-dev" "jdk8/jdk8" "jdk8u/jdk8u" "jdk8u/jdk8u-dev" "aarch64-port/jdk8" "aarch64-port/jdk8u" "shenandoah/jdk8" "aarch64-port/jdk8u-shenandoah"

      - uses: eine/tip@master
        with:
          tag: hg-files-latest
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            hg-jdkforest-corba.tar.xz
            hg-jdkforest-hotspot.tar.xz
            hg-jdkforest-jaxp.tar.xz
            hg-jdkforest-jaxws.tar.xz
            hg-jdkforest-jdk.tar.xz
            hg-jdkforest-langtools.tar.xz
            hg-jdkforest-nashorn.tar.xz
            hg-jdkforest-top.tar.xz
